### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by John520** [chwshuang/web#4]
我是一个新手，对IDEA不是很熟悉，我启动以后说包没找到是什么原因
Artifact back:war exploded: com.intellij.javaee.oss.admin.jmx.JmxAdminException: com.intellij.execution.ExecutionException: D:\web\back\target\back-1.0-SNAPSHOT not found for the web module.
ps:有没有学习IDEA的资料推荐一下，之前一直用的Eclipse。

**Comment by chwshuang** [comment]
在Idea项目的Models Setting中，新建一个Tomcat Server，然后在【Deployment】中添加一个【Artifact】,选中back:war exploded即可。

**Comment by MrXYi** [comment]
导入报错，update也没用
![image](https://user-images.githubusercontent.com/28567980/35263768-0b8ea4e6-0055-11e8-9335-ff75564338fc.png)
