### ISSUE TITLE
我想问下.我做到第三步了,做一个登录,但是好像视图解析器出问题了,跳转不到主页,

### ISSUE THREAD

**Issue by fuckSpider** [chwshuang/web#8]
![tim 20180418105427](https://user-images.githubusercontent.com/31839800/38909363-e4ff8ab8-42f6-11e8-8dc5-1fc3309b6a2a.png)

**Comment by chwshuang** [comment]
开启debug日志，查看日志中的请求处理流程

**Comment by andyyhh** [comment]
_leanning...._
